version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-rickmorty
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rickmorty
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - ricknet
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-rick
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ricknet
    restart: always

networks:
  ricknet:

volumes:
  pgdata:
