apiVersion: apps/v1
kind: Deployment
metadata:
  name: Teste-git
spec:
  selector:
    matchLabels:
      app: Teste
  replicas: 1
  template:
    metadata:
      labels:
        app: Teste
    spec:
      containers:
      - name: Teste
        image: Teste
        volumeMounts:
        - name: vmfs-vmdk-storage
          mountPath: /data/
      volumes:
      - name: vmfs-vmdk-storage
        vsphereVolume:
          volumePath: "[Datastore] volumes/testdir"
          fsType: ext4
